server:
  serviceName: cartservice
  hostPort: :6005

database:
  driver: mysql
  hostPort: :3306
  username: root
  password: root
  database: belajar-microservice

redis:
  hostPort: :6379
  username:
  password:
  dbNumber: 1