server:
  hostPort: :6001

service:
  product:
    serviceName: productservice
    hostPort: :6004
  merchant:
    serviceName: merchantservice
    hostPort: :6002
  customer:
    serviceName: customerservice
    hostPort: :6003
  cart:
    serviceName: cartservice
    hostPort: :6005

jwt:
  expiredIn: 1
  signingKey: ilhamnadhif
