server:
  hostPort: :6001

service:
  product:
    serviceName: productservice
    hostPort: :6010
  merchant:
    serviceName: merchantservice
    hostPort: :6010
  auth:
    serviceName: authservice
    hostPort: :6010
