// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/auth.proto

package proto

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AuthService service

func NewAuthServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for AuthService service

type AuthService interface {
	LoginMerchant(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*TokenResponse, error)
	LoginCustomer(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*TokenResponse, error)
}

type authService struct {
	c    client.Client
	name string
}

func NewAuthService(name string, c client.Client) AuthService {
	return &authService{
		c:    c,
		name: name,
	}
}

func (c *authService) LoginMerchant(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*TokenResponse, error) {
	req := c.c.NewRequest(c.name, "AuthService.LoginMerchant", in)
	out := new(TokenResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) LoginCustomer(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*TokenResponse, error) {
	req := c.c.NewRequest(c.name, "AuthService.LoginCustomer", in)
	out := new(TokenResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthService service

type AuthServiceHandler interface {
	LoginMerchant(context.Context, *LoginReq, *TokenResponse) error
	LoginCustomer(context.Context, *LoginReq, *TokenResponse) error
}

func RegisterAuthServiceHandler(s server.Server, hdlr AuthServiceHandler, opts ...server.HandlerOption) error {
	type authService interface {
		LoginMerchant(ctx context.Context, in *LoginReq, out *TokenResponse) error
		LoginCustomer(ctx context.Context, in *LoginReq, out *TokenResponse) error
	}
	type AuthService struct {
		authService
	}
	h := &authServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AuthService{h}, opts...))
}

type authServiceHandler struct {
	AuthServiceHandler
}

func (h *authServiceHandler) LoginMerchant(ctx context.Context, in *LoginReq, out *TokenResponse) error {
	return h.AuthServiceHandler.LoginMerchant(ctx, in, out)
}

func (h *authServiceHandler) LoginCustomer(ctx context.Context, in *LoginReq, out *TokenResponse) error {
	return h.AuthServiceHandler.LoginCustomer(ctx, in, out)
}
